package cc.factorie.app.nlp.lexicon.wikipedia

import cc.factorie.app.nlp.lexicon.ProvidedTriePhraseLexicon
import cc.factorie.util.ModelProvider

/**
 * @author johnsullivan
 */
class Battle()(implicit mp:ModelProvider[Battle]) extends ProvidedTriePhraseLexicon[Battle]
class BattleRedirect()(implicit mp:ModelProvider[BattleRedirect]) extends ProvidedTriePhraseLexicon[BattleRedirect]
class BattleAndRedirect()(implicit mp:ModelProvider[BattleAndRedirect]) extends ProvidedTriePhraseLexicon[BattleAndRedirect]
class BattleDisambiguation()(implicit mp:ModelProvider[BattleDisambiguation]) extends ProvidedTriePhraseLexicon[BattleDisambiguation]
class Book()(implicit mp:ModelProvider[Book]) extends ProvidedTriePhraseLexicon[Book]
class BookRedirect()(implicit mp:ModelProvider[BookRedirect]) extends ProvidedTriePhraseLexicon[BookRedirect]
class BookAndRedirect()(implicit mp:ModelProvider[BookAndRedirect]) extends ProvidedTriePhraseLexicon[BookAndRedirect]
class BookDisambiguation()(implicit mp:ModelProvider[BookDisambiguation]) extends ProvidedTriePhraseLexicon[BookDisambiguation]
class Business()(implicit mp:ModelProvider[Business]) extends ProvidedTriePhraseLexicon[Business]
class BusinessRedirect()(implicit mp:ModelProvider[BusinessRedirect]) extends ProvidedTriePhraseLexicon[BusinessRedirect]
class BusinessAndRedirect()(implicit mp:ModelProvider[BusinessAndRedirect]) extends ProvidedTriePhraseLexicon[BusinessAndRedirect]
class BusinessDisambiguation()(implicit mp:ModelProvider[BusinessDisambiguation]) extends ProvidedTriePhraseLexicon[BusinessDisambiguation]
class Competition()(implicit mp:ModelProvider[Competition]) extends ProvidedTriePhraseLexicon[Competition]
class CompetitionRedirect()(implicit mp:ModelProvider[CompetitionRedirect]) extends ProvidedTriePhraseLexicon[CompetitionRedirect]
class CompetitionAndRedirect()(implicit mp:ModelProvider[CompetitionAndRedirect]) extends ProvidedTriePhraseLexicon[CompetitionAndRedirect]
class CompetitionDisambiguation()(implicit mp:ModelProvider[CompetitionDisambiguation]) extends ProvidedTriePhraseLexicon[CompetitionDisambiguation]
class Event()(implicit mp:ModelProvider[Event]) extends ProvidedTriePhraseLexicon[Event]
class EventRedirect()(implicit mp:ModelProvider[EventRedirect]) extends ProvidedTriePhraseLexicon[EventRedirect]
class EventAndRedirect()(implicit mp:ModelProvider[EventAndRedirect]) extends ProvidedTriePhraseLexicon[EventAndRedirect]
class EventDisambiguation()(implicit mp:ModelProvider[EventDisambiguation]) extends ProvidedTriePhraseLexicon[EventDisambiguation]
class Film()(implicit mp:ModelProvider[Film]) extends ProvidedTriePhraseLexicon[Film]
class FilmRedirect()(implicit mp:ModelProvider[FilmRedirect]) extends ProvidedTriePhraseLexicon[FilmRedirect]
class FilmAndRedirect()(implicit mp:ModelProvider[FilmAndRedirect]) extends ProvidedTriePhraseLexicon[FilmAndRedirect]
class FilmDisambiguation()(implicit mp:ModelProvider[FilmDisambiguation]) extends ProvidedTriePhraseLexicon[FilmDisambiguation]
class Location()(implicit mp:ModelProvider[Location]) extends ProvidedTriePhraseLexicon[Location]
class LocationRedirect()(implicit mp:ModelProvider[LocationRedirect]) extends ProvidedTriePhraseLexicon[LocationRedirect]
class LocationAndRedirect()(implicit mp:ModelProvider[LocationAndRedirect]) extends ProvidedTriePhraseLexicon[LocationAndRedirect]
class LocationDisambiguation()(implicit mp:ModelProvider[LocationDisambiguation]) extends ProvidedTriePhraseLexicon[LocationDisambiguation]
class ManMadeThing()(implicit mp:ModelProvider[ManMadeThing]) extends ProvidedTriePhraseLexicon[ManMadeThing]
class ManMadeThingRedirect()(implicit mp:ModelProvider[ManMadeThingRedirect]) extends ProvidedTriePhraseLexicon[ManMadeThingRedirect]
class ManMadeThingAndRedirect()(implicit mp:ModelProvider[ManMadeThingAndRedirect]) extends ProvidedTriePhraseLexicon[ManMadeThingAndRedirect]
class ManMadeThingDisambiguation()(implicit mp:ModelProvider[ManMadeThingDisambiguation]) extends ProvidedTriePhraseLexicon[ManMadeThingDisambiguation]
class Organization()(implicit mp:ModelProvider[Organization]) extends ProvidedTriePhraseLexicon[Organization]
class OrganizationRedirect()(implicit mp:ModelProvider[OrganizationRedirect]) extends ProvidedTriePhraseLexicon[OrganizationRedirect]
class OrganizationAndRedirect()(implicit mp:ModelProvider[OrganizationAndRedirect]) extends ProvidedTriePhraseLexicon[OrganizationAndRedirect]
class OrganizationDisambiguation()(implicit mp:ModelProvider[OrganizationDisambiguation]) extends ProvidedTriePhraseLexicon[OrganizationDisambiguation]
class Person()(implicit mp:ModelProvider[Person]) extends ProvidedTriePhraseLexicon[Person]
class PersonRedirect()(implicit mp:ModelProvider[PersonRedirect]) extends ProvidedTriePhraseLexicon[PersonRedirect]
class PersonAndRedirect()(implicit mp:ModelProvider[PersonAndRedirect]) extends ProvidedTriePhraseLexicon[PersonAndRedirect]
class PersonDisambiguation()(implicit mp:ModelProvider[PersonDisambiguation]) extends ProvidedTriePhraseLexicon[PersonDisambiguation]
class Song()(implicit mp:ModelProvider[Song]) extends ProvidedTriePhraseLexicon[Song]
class SongRedirect()(implicit mp:ModelProvider[SongRedirect]) extends ProvidedTriePhraseLexicon[SongRedirect]
class SongAndRedirect()(implicit mp:ModelProvider[SongAndRedirect]) extends ProvidedTriePhraseLexicon[SongAndRedirect]
class SongDisambiguation()(implicit mp:ModelProvider[SongDisambiguation]) extends ProvidedTriePhraseLexicon[SongDisambiguation]
